### ISSUE TITLE
The first example in "5. A syntax-parse crash course"

### ISSUE THREAD

**Issue by soegaard** [syntax-objects/syntax-parse-example#20]
I know the point of the example is that the use of a high level
construct such as `syntax-parse` is better than using a low level
construct such as `syntax-e`, but I think using `syntax->list` is
easier to grasp for someone new to macros.

Maybe something a la this?

```
(define-syntax (K name+args-stx)
  (define args (cdr (syntax->list name+args-stx)))
  (if (= (length args) 2)
    (car args)
    (raise-argument-error
    'K
    "syntax object containing a list with 3 elements"
    name+args-stx)))
```

**Comment by bennn** [comment]
I picked `syntax-e` because it's the basic accessor, like car and cdr.

(There's also some personal preference. I rarely use `syntax->list` in my own code.)
